week4/sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'

end

week4/sample_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

week4/sample_app/app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title='')
		base_title="Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else 
			"#{page_title}| #{base_title}"
		end
	end
end

week4/sample_app/app/helpers/users_helper.rb
module UsersHelper
end

week4/sample_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

week4/sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home",  root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

week4/sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
<%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
 <%= render 'layouts/header' %>
<div class="container">
	<%= yield %>
	<%= render 'layouts/footer' %>
</div>
</body>
</html>

week4/sample_app/app/views/static_pages/about.html.erb
<% provide(:title , "About") %>
<!DOCTYPE html>
<html>
<head>
	<title><%=yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
</head>
<body>
<h1>About</h1>
<p>
The <a href="http://www.railstutorial.org/"><i><b>Ruby on Rails Tutorial</b></i></a> is a <a href="http://www.railstutorial.org/book">book</a> and <a href="http://screencasts.railstutorial.org">screencast series</a> to teach web development with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This is the sample application for the tutorial.
</p>
</body>
</html>

week4/sample_app/app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
<head>
	<title><%=yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
</head>
<body>
<h1>Contact</h1>
<p class="center">Contact the Ruby on Rails Tutorial about the sample app at the <a href="http://www.railstutorial.org/#contact"> Contact page</a>.
</p>
</body>
</html>

week4/sample_app/app/views/static_pages/help.html.erb
<% provide(:title , "Help") %>
<!DOCTYPE html>
<html>
<head>
	<title><%=yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
</head>
<body>
<h1>Help</h1>
<p>Get help on the Ruby on Rails Tutorial at the <a href="http://www.railstutorial.org/#help">Rails tutorial help section</a>. To get help on this sample app, see the <a href="http://www.railstutorial.org/book"><i><b>Ruby on rails tutorial</b></i></a> book.</p>
</body>
</html>

week4/sample_app/app/views/static_pages/home.html.erb
<% provide(:title , "Home") %>
<!DOCTYPE html>
<html>
<head>
	<title><%=yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
</head>
<body>
<div class="center jumbotron">
<h1>Welcom to the Sample App</h1>
<h2>This is home page for the <a href="http://www.railstutorial.org/">Ruby on rails Tutorial</a> sample application.</h2> 
<%= link_to "Sign up now!", signup_path,class:"btn btn-lg btn-primary" %>
</div>
<a href="http://rubyonrails.org/"><img src="/assets/rails-9308b8f92fea4c19a3a0d8385b494526.png" /></a>
</body>
</html>

week4/sample_app/app/views/users/new.html.erb
<% provide(:title , 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users</p>